version: '3'
services:
  mysql_57:
    container_name: mysql_57
    image: amd64/mysql:5.7
    volumes:
    - /Users/daviddew/Documents/Repositories/Docker-Compose-For-Dev/mysql-57/data:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=base
    - MYSQL_USER=base
    - MYSQL_PASSWORD=base
    ports:
    - "3308:3306"