version: '3'
services:
  mysql_56_lowercase:
    container_name: mysql_56_lowercase
    image: mysql:5.6
    volumes:
    - /home/david/Docker-Compose-For-Dev/mysql-56-lowercase/data:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=base
    - MYSQL_USER=base
    - MYSQL_PASSWORD=base
    ports:
    - "3305:3306"
    command: mysqld --lower_case_table_names=1