version: '3'
services:
  mysql_57:
    container_name: mysql_57
    image: mysql:5.7
    volumes:
      - ~/docker-data/mysql-57:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=base
    - MYSQL_USER=base
    - MYSQL_PASSWORD=base
    ports:
    - "3308:3306"