version: '3'
services:
  mysql_56:
    container_name: mysql_56
    image: mysql:5.6
    volumes:
    - /home/david/Docker-Compose-For-Dev/mysql-56/data:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=base
    - MYSQL_USER=base
    - MYSQL_PASSWORD=base
    ports:
    - "3309:3306"