version: '3'
services:
  mariadb_10_3:
    container_name: mariadb_10_3
    image: amd64/mariadb:10.3-bionic
    volumes:
    - /Users/daviddew/Documents/Repositories/Docker-Compose-For-Dev/mariadb-10-3/data:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=base
    - MYSQL_USER=base
    - MYSQL_PASSWORD=base
    ports:
    - "3302:3306"
