version: '3'
services:
  mysql_8:
    container_name: mysql_8
    image: mysql:8
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=base
    - MYSQL_USER=base
    - MYSQL_PASSWORD=base
    ports:
    - "3303:3306"
