version: '3'
services:
  mysql_8:
    container_name: mysql_8
    image: mysql:8
    volumes:
    - /home/david/Docker-Compose-For-Dev/mysql-8/data:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=base
    - MYSQL_USER=base
    - MYSQL_PASSWORD=base
    ports:
    - "3303:3306"
